name: nyc-taxi

channels:
- defaults
- conda-forge

dependencies:
- python==3.6.6
- pip==18.1
- jupyter==1.0.0
- jupyter_contrib_nbextensions==0.5.0
- jupyter_nbextensions_configurator==0.4.0
- jupyterlab==0.35.4
- geoviews

- pip:
  # General Python
  - pytest==4.0.0
  - tqdm==2.2.4
  - dask[complete]==0.20.1
  - dill==0.2.8.2
  - networkx==1.11
  - sphinx==1.8.1
  - sphinx_rtd_theme==0.4.2

  # Data science / ML
  - matplotlib==3.0.0
  - numpy==1.15.2
  - pandas==0.23.4
  - scipy==1.1.0
  - plotly==3.3.0
  - seaborn==0.9.0
  - statsmodels==0.9.0
  - shapely==1.6.4.post2
  - geopandas==0.4.0
  - datashader==0.6.8
  - bokeh==1.0.1
  - holoviews==1.10.9
  - paramnb==2.0.4
  - scikit-learn==0.20.0
